# Reload from an action

name: Test

on:
  push

jobs:
  perl:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        sudo cpan -T -i GitHub::Crud  

    - name: Test
      run: |
        date >  zzz.txt
        date >> zzz.txt
        date >> zzz.txt
        echo "BBBB" >> zzz.txt
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} perl -M"GitHub::Crud" -e"writeFileFromFileFromCurrentRun q(zzz.txt);"
